### ISSUE TITLE
Which Firmware to use?

### ISSUE THREAD

**Issue by Diddlik** [xyzroe/ZigStarGW-FW#1]
I'm a little confused about what to use. 
There is a possibility ESPHOME and there is another version of the firmware (https://github.com/xyzroe/ZigStarGW-FW).
Which one is better to use?

**Comment by mercenaruss** [comment]
@Diddlik I recommend using this one in the repo for future, all new features will be added here.

**Comment by Diddlik** [comment]
@mercenaruss ok, this is a good point.
