### ISSUE TITLE
Ability to reset login password

### ISSUE THREAD

**Issue by Diddlik** [xyzroe/ZigStarGW-FW#15]
Unfortunately, it always happens that you assign a password and forget it. Without resetting the device, it would be good to have the possibility to reset it.

**Comment by xyzroe** [comment]
7798ec383302ccfa7d23e9bdd0191deb37643cce

**Comment by Andrejsinizin** [comment]
Возможно сбросить пароль для входа в веб-интерфейс

**Comment by xyzroe** [comment]
@Andrejsinizin 
First of all, you should look for the answer in the documentation.
Moreover, there is a specific link to it right above your message.

Secondly, when you write somewhere, have respect to follow the accepted rules of communication, in this case use English.
