### ISSUE TITLE
DS18B20 sensor is not queried

### ISSUE THREAD

**Issue by Diddlik** [xyzroe/ZigStarGW-FW#19]
On the new Olizig POE, DS18b20 sensor is not polled. Most likely it is due to the configuration, 
the OliZig gets borad id = 1, but when querying the sensor, board id = 2 is expected.  See below:

![grafik](https://user-images.githubusercontent.com/6010713/202529578-38338ccb-05da-4b59-a0f9-dd6aaa5b3478.png)

![grafik](https://user-images.githubusercontent.com/6010713/202529679-a6f18dd5-d9c4-48dc-b3e8-7993c877234a.png)

**Comment by xyzroe** [comment]
@Diddlik Could you please test new bin file in https://github.com/xyzroe/ZigStarGW-FW/tree/main/bin ?
If everything is ok, I will release it.

**Comment by Diddlik** [comment]
> @Diddlik Could you please test new bin file in https://github.com/xyzroe/ZigStarGW-FW/tree/main/bin ? If everything is ok, I will release it.

Seem to work! Thank you!
![grafik](https://user-images.githubusercontent.com/6010713/202840671-b8ed03e6-22e6-4065-b840-b4552438bf44.png)
