### ISSUE TITLE
Dallas DS18b20 sensor suddenly only 0C°

### ISSUE THREAD

**Issue by Diddlik** [xyzroe/ZigStarGW-FW#23]
At first everything worked fine. The values of dallas were about on the level of ESP Sensor. The coordinator was not even touched. Still works fine, only dallas sensor no longer and delivers only 0

![grafik](https://user-images.githubusercontent.com/6010713/209404080-9784f2b9-6cc8-4d53-8cc2-40fd714c11a4.png)

**Comment by Diddlik** [comment]
some update:
After soft reboot no temperature update
After hard reboot (power off, power on) dallal works again

![Screenshot_2023-01-10-20-38-26-48_f9ee0578fe1cc94de7482bd41accb329.jpg](https://user-images.githubusercontent.com/6010713/211646004-e45022ec-9ce0-4854-8ef5-241343c95fe5.jpg)

**Comment by xyzroe** [comment]
I think the problem is in the sensor.
If it was a firmware issue, a soft reboot would probably help too.

**Comment by Diddlik** [comment]
Ok, possibly ordinary china scrap
