### ISSUE TITLE
Flash cc2538//cc2652 from WebUI

### ISSUE THREAD

**Issue by tks09** [xyzroe/ZigStarGW-FW#25]
Hey

We're currently like to be able to download the firmware for cc2538/cc2652 from the internet and flash it to the controller just by using the ZigStarGW-FW WebUI.
To do that, we would be happy to fork it, implement it and if course do a pullrequest on your main repo to give it back to the community. So it's not exactly a feature request but just a request for information on your thoughts about this.

My main question is:
I currently suspect that your reason to develop a the firmware downloader in python and flash over TCP is that you would like to make it compatible to other controllers without touching the firmware, but just patching the code on python level.
**Did you have any other reasons not to do it in the Arduino Firmware which I currently don't see?**

**Comment by xyzroe** [comment]
Hello!
Great idea, I would appreciate your implementation.
I did it in python just because it was faster.

**Comment by tsmt09** [comment]
Great to hear. I will get my hands on soon =)

**Comment by xyzroe** [comment]
Look at [XZG Firmware](http://github.com/xyzroe/XZG)
