### ISSUE TITLE
Delay on outgoing packets send while high load on Zigbee network

### ISSUE THREAD

**Issue by Hashira-ira** [xyzroe/ZigStarGW-FW#5]
While the network coordinator is loaded with constant incoming traffic (at least 1 message every second) outgoing requests from z2m are sent with a delay.
There is no delay in receiving incoming packages in any conditions.

FW version: 0.6.0

Если сетевой координатор будет загружен постоянно входящим трафиком каждую секунду и в этом момент делать запросы на исходящие действия то действия выполняются с таймингом задержкой. FW version : 0.6.0

**Comment by xyzroe** [comment]
@Hashira-ira please check this one [tag/0.6.1](https://github.com/xyzroe/ZigStarGW-FW/releases/tag/0.6.1)

**Comment by xyzroe** [comment]
I have 3 devices on my test network
Each of them sends 8 messages to the network every 1 second.

On version 0.6.0, the commands were executed with a delay starting from 10 seconds and up to several minutes even, or might not be executed at all.

On version 0.6.1, commands are executed almost instantly.
