### ISSUE TITLE
[Request] Support disabling Leds

### ISSUE THREAD

**Issue by CSchoch** [xyzroe/ZigStarGW-FW#6]
Hi, 
is it possible to support disabling Leds from Z2M?
Or at least from Webinterface

KR Christian

**Comment by xyzroe** [comment]
Hello Christian!

The ZigStarGW-FW firmware controls the operation of the ESP32 and therefore cannot affect the operation of the Zigbee module LEDs.

In order for you to control the operation of the LEDs from z2m, the Zigbee module firmware must support it, for example, the [firmware from Koen](https://github.com/Koenkk/Z-Stack-firmware/tree/master/coordinator/Z-Stack_3.x.0/bin)

For flashing, you can use [ZigStarGW-MT](https://github.com/xyzroe/ZigStarGW-MT).
