### ISSUE TITLE
Compile firmware error

### ISSUE THREAD

**Issue by Tao173** [xyzroe/ZigStarGW-FW#7]
I use VS to compile the firmware, but it gives an error.
log:

Compiling .pio\build\prod\libc78\LittleFS_esp32\littlefs_api.c.o
.pio/libdeps/prod/LittleFS_esp32/src/LITTLEFS.cpp: In member function 'virtual bool LITTLEFSImpl::exists(const char*)':
.pio/libdeps/prod/LittleFS_esp32/src/LITTLEFS.cpp:44:28: error: no matching function for call to 'LITTLEFSImpl::open(const char*&, const char [2])'
     File f = open(path, "r");
                            ^
In file included from .pio/libdeps/prod/LittleFS_esp32/src/LITTLEFS.cpp:17:
C:/users/wanzi/.platformio/packages/framework-arduinoespressif32/libraries/FS/src/vfs_api.h:38:17: note: candidate: 'virtual fs::FileImplPtr VFSImpl::open(const char*, const char*, bool)'
     FileImplPtr open(const char* path, const char* mode, const bool create) override;
                 ^~~~
C:/users/wanzi/.platformio/packages/framework-arduinoespressif32/libraries/FS/src/vfs_api.h:38:17: note:   candidate expects 3 arguments, 2 provided

**Comment by xyzroe** [comment]
I think you have a problem with the libraries.
Perhaps the version is wrong or the library is completely wrong.
