### ISSUE TITLE
ZigStar Ethernet GW: get MQTT socket state and reboot cmd

### ISSUE THREAD

**Issue by roobbb** [xyzroe/ZigStarGW-FW#9]
Hello.

I have bought your ZigStar Ethernet GW which is working very well and I really appreciate it (it's working inside a DIN rail box). 
It is absolutely worth the money. Great work!

Even the MQTT functionality (sending information of the GW itself) comes in very handy. 
I have noticed the following behavior while having the GW running:
1) socket report over MQTT
When the GW was started and zigbee2mqtt is online, the GW reports socket as ON. Unfortunately after almost 5 days the GW reports socket OFF, but zigbee2mqtt is still online. Even when I check the ZigstarGW web interface, it states there socket is online by a green check mark.
When I restart zigbee2mqtt or the GW it reports socket ON again. But 5 days later it reports socket OFF.
All other MQTT reports, e.g. temperature, are still working fine.  

2) Web interface of the GW
About ten days after the socket is reported as OFF the web interface of the GW becomes unreachable. 

I tried to reboot the GW be sending out "ZigStarGW-9549/cmd {cmd:"rst_esp"}" but it didn't help in both cases. I have to power it off and on to get the web interface back and I have to restart zigbee2mqtt to get the socket state.

3) restart Zigbee module
Because of 1) and 2) I even tried the MQTT command ZigStarGW-9549/cmd {cmd:"rst_zig"} to restart the Zigbee module. I tested it several times and after that the Zigbee system stopped its communication. I had to take off the GW's power again.

Could you please help me with these questions:
Is it possible to implement: 
- a MQTT set command what reboots the entire GW? 
So I could be able to reboot it periodically.
- a MQTT get command which gets the actual socket state?
So I could send it out of my smart home system periodically and pull the information actively.
- What does the MQTT command "{cmd:"rst_zig"} - restart Zigbee module" exactly do?

Thank you very much and kind regards

---------- some screenshots ---------------------------
socket state in ZigStar webif
![ZigstarGW_MQTT_state_in_smarthome](https://user-images.githubusercontent.com/43150729/150080900-25c181a0-f3ad-4664-b796-0498ff41e1a1.jpg)

socket state in my smart home system
![ZigstarGW_webif](https://user-images.githubusercontent.com/43150729/150080936-34819b05-7473-4c6c-a8c9-f1e4b8741d71.jpg)

**Comment by xyzroe** [comment]
Greetings!

Thank you for your observations and detailed description of the noticed bugs.

1 and 2 I will try to repeat them and after I will search and fix it.
3. After restarting the Zigbee module, of course, the network operation stops, it is necessary to restart the zigbee2mqtt. There is no need to reboot the power gateway.

Your questions:
1. Reboot ESP reboots the entire gateway.
2. The status of the socket connection is already visible in MQTT, it does not need to be requested. 
3. Restart Zigbee module just restart Zigbee module using RST pin.

**Comment by roobbb** [comment]
Hello.

Thank you very much for your quick response 😀
I was not sure if the behavior I observed was actually caused by bugs. This is what you can say far better than me of course. So I stay tuned for the results you will find out. Please let me know if you need further information or testing.

Best regards

**Comment by xyzroe** [comment]
On the first point - there was an understanding where the problem came from. If the socket connection rises faster than the MQTT, then report as OFF. There will be a fix soon.

The second point - with an inaccessible web interface, there is no possibility to repeat it yet, the uptime is too small.
I accidentally rebooted because I mixed up the IP addresses.

**Comment by xyzroe** [comment]
> 1. Reboot ESP reboots the entire gateway.

My mistake. Reboot ESP reboots just ESP, without Zigbee. 
To reboot entire GW you need to send command to reboot zigbee and then another command to reboot ESP.
